variable "tfi_region" {}
variable "tfi_win_security_grp" {}
variable "tfi_lx_security_grp" {}
variable "tfi_key_pair_name" {}
variable "tfi_subnet_id" {}
variable "tfi_vpc_id" {}
variable "tfi_cb_ip" {}
variable "tfi_win_instances" {}
variable "tfi_lx_instances" {}
variable "tfi_private_key" {}
variable "tfi_public_key" {}
variable "tfi_rm_pass" {}
variable "tfi_rm_user" {}
variable "tfi_ssh_user" {}
variable "tfi_instance_profile" {}
variable "tfi_assign_public_ip" {}
variable "tfi_win_instance_type" {}
variable "tfi_lx_instance_type" {}
variable "tfi_git_repo" {}
variable "tfi_git_ref" {}
variable "tfi_common_args" {}
variable "tfi_win_args" {}
variable "tfi_lx_args" {}
variable "tfi_win_userdata_log" {}
variable "tfi_lx_userdata_log" {}
variable "tfi_s3_bucket" {}
variable "tfi_build_date" {}
variable "tfi_build_id" {}
variable "tfi_instance_name_tag" {}
