variable "tfi_region" {}
variable "tfi_win_security_grp" {}
variable "tfi_lx_security_grp" {}
variable "tfi_key_pair_name" {}
variable "tfi_subnet_id" {}
variable "tfi_vpc_id" {}
variable "tfi_cb_ip" {}
variable "tfi_build_win" {}
variable "tfi_build_lx" {}
variable "tfi_private_key" {}
variable "tfi_public_key" {}
variable "tfi_rm_pass" {}
variable "tfi_rm_user" {}
variable "tfi_ssh_user" {}
variable "tfi_instance_profile" {}
variable "tfi_assign_public_ip" {}
variable "tfi_win_instance_type" {}
variable "tfi_lx_instance_type" {}
variable "tfi_repo" {}
variable "tfi_branch" {}
variable "tfi_common_args" {}
variable "tfi_win_args" {}
variable "tfi_lx_args" {}
variable "tfi_win_userdata_log" {}
variable "tfi_lx_userdata_log" {}
variable "tfi_lx_instances" {}
variable "tfi_win_instances" {}
